server:
  port: 8081
---
spring:
  application:
    name: Junior-Java-Developer-BVP-Software
  mail:
    host: smtp-mail.outlook.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: ${spring.mail.port}
    username: ${spring.mail.username}
    password: ${spring.mail.password}
  sql:
    init:
      mode: never
  flyway:
    baseline-on-migrate: true
  datasource:
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
---
security:
  jwt:
    token:
      secret-key: ${random.value}
      expire-milliseconds: 12000000000
    refresh-token:
      expire-milliseconds: 24000000000
---
logging:
  level:
    org.springframework.transaction.interceptor: off
    org.springframework.security: DEBUG
